accounts/urls.py
from django.conf.urls import patterns, include, url
from accounts import views
urlpatterns = patterns('',
  url(r'^register/', views.SignUpView.as_view(), name = 'register'),
  url(r'^login/', 'django.contrib.auth.views.login', {'template_name':'accounts/login.html'}, name = 'login'),
  url(r'^logout/', 'django.contrib.auth.views.logout', {'template_name':'accounts/logged_out.html'}, name = 'logout'),
  url(r'^profile/', views.profile, name = 'profile'),
)

wujing/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'wujing.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^auth/', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace = 'accounts')),
    url(r'^chatroom/', include('chatroom.urls', namespace = 'chatroom')),
    url(r'^board/', include('msgboard.urls', namespace = 'msgboard')),
    url(r'^psytest/', include('psytest.urls', namespace = 'psytest')),
)

accounts/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from django.forms import widgets
from django.contrib.auth.models import User
import re

class SignUpForm(forms.Form):
    username = forms.CharField(label='用户名', max_length = 20)
    password = forms.CharField(label='密码', widget = widgets.PasswordInput)
    password_again = forms.CharField(label='密码', widget = widgets.PasswordInput)

    def clean_username(self):
    	data = self.cleaned_data['username']
    	prog = re.compile(r'[a-zA-Z0-9_]+')
    	if not prog.match(data):
    		raise forms.ValidationError('用户名只能包含英文字符，数字及下划线', code='invalid_username')
    	if User.objects.filter(username = data):
    		raise forms.ValidationError("用户名已经存在", code='username_exists')
    	return data

    def clean_password_again(self):
        data = self.cleaned_data['password_again']
        if not data == self.cleaned_data['password']:
            raise forms.ValidationError('两次密码不相同', code='password_again_err')

class SignInForm(forms.Form):
    username = forms.CharField(label='用户名', max_length = 20)
    password = forms.CharField(label='密码', widget = widgets.PasswordInput)

class ChangePasswdForm(forms.Form):
    password_old = forms.CharField(label='旧密码')
    password = forms.CharField(label='新密码')
    password_again = forms.CharField(label='新密码')

    def clean_password_again(self):
        data = self.cleaned_data['password_again']
        if not data == self.cleaned_data['password']:
            raise forms.ValidationError('两次密码不相同', code='password_again_err')

accounts/views.py
from django.shortcuts import render
from django.views.generic import View
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from accounts.forms import SignUpForm, SignInForm

# Create your views here.
class SignUpView(View):
    def get(self, request):
        form = SignUpForm()
        return render(request, 'accounts/register.html', {'form':form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if not form.is_valid():
            return render(request, 'accounts/register.html', {'form':form})
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = User.objects.create_user(username = username, password = password)
        return render(request, 'accounts/register-ok.html', {'user':user})

@login_required
def profile(request):
    user = request.user
    return render(request, 'accounts/profile.html', {'user':user})

accounts/templates/accounts/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
		<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% static "css/ie.css" %}" /><![endif]-->
		{% block extrastyle %}{% endblock %}
		<script src="{% static 'js/jquery.min.js' %}"></script>
		{% block extrahead %}{% endblock %}
	</head>
	<body class="{% block bodyclass %}{% endblock %}">
		<div id="container">
		<!-- Header -->
		<div id="header">
			<div id="branding">
				{%block branding %}{% endblock %}
			</div>
			{% if user.is_active %}
			<div id="user-tools">
				{% block welcome-msg%}欢迎 {{user.username}}{% endblock %}
				{% block userlinks %}
				 | <a href="{% url 'accounts:logout' %}">注销</a>
				{% endblock %}
			</div>
			{% endif %}
			{% block nav-global %}{% endblock %}
		</div>
		<!-- END Header-->
		{% block breadcrumbs %}{% endblock %}

		<!-- Content -->
		<div id="content" class="{% block coltype %}{% endblock %}">
			{% block pretitle %}{% endblock %}
			{% block content_title %}{% endblock %}
			{% block content %}{% endblock %}
			{% block sidebar %}{% endblock %}
		</div>
		<!-- END Content -->

		{% block footer %}{% endblock %}
		</div>
	</body>
</html>

accounts/templates/accounts/logged_out.html
{% extends "accounts/base.html" %}
{% block title %}
用户后台
{% endblock %}

{% block branding %}
<h1>用户后台界面</h1>
{% endblock %}

{% block content %}
<h2>您已经登出系统。</h2>
<a href="{% url 'accounts:login' %}">再次登入</a>
{% endblock %}

accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}
{% load staticfiles %}
{% block extrastyle %}
{{block.supper}}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/login.css'%}"/>
{% endblock %}

{% block title %}登入{% endblock %}
{% block branding %}
<h1>登入系统</h1>
{% endblock %}

{% block bodyclass %} login{% endblock %}


{% block content %}
<div id="content-main colM">
	<form action="{% url 'django.contrib.auth.views.login' %}"
				method="post">
	{% csrf_token %}
	<div class="form-row">
		<label for="id_username" class="required">
			用户名:
		</label>
		{{form.username}}
	</div>
	<div class="form-row">
		<label for="id_password" class="required">
			密码:
		</label>
		{{form.password}}
		<input type="hidden" name="next" value="{{ next }}" />
	</div>
	<div class="submit-row">
		<label>&nbsp;</label><input type="submit" value="登入"/> | 
		<a href="{% url 'accounts:register' %}">注册</a>
	</div>
	</form>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'accounts/base.html' %}

{% block title %}
用户后台
{% endblock %}

{% block branding %}
<h1>用户后台界面</h1>
{% endblock %}

{% block content %}
<h1>欢迎 {{user.username}}</h1>
{% endblock %}

accounts/templates/accounts/register-ok.html
{% extends "accounts/base.html" %}
{% block title %}
注册成功
{% endblock %}

{% block branding %}
<h1>注册成功</h1>
{% endblock %}

{% block content %}
<h2>恭喜您已经注册成功。</h2>
<a href="{% url 'accounts:login' %}">请点此登入</a>
{% endblock %}

accounts/templates/accounts/register.html
{%extends "accounts/base.html"%}
{% load staticfiles %}

{% block extrastyle %}
{{block.supper}}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/css/login.css'%}"/>
{% endblock %}

{% block title %}注册{% endblock %}
{% block branding %}<h1>注册系统</h1>{% endblock %}

{% block bodyclass %} login{% endblock %}

{% block content %}
<div id="content-main colM">
	<form action="{% url 'accounts:register' %}" method="post" class="form-horizontal">
    {% csrf_token %}
		<div class="form-row">
			{{ form.username.errors }}
			<label for="id_username" class="required">
				用户名:
			</label>
			{{form.username}}
		</div>
		<div class="form-row">
			{{ form.password.errors }}
			<label for="id_password" class="required">
				密码:
			</label>
			{{form.password}}
		</div>
		<div class="form-row">
			{{ form.password_again.errors }}
			<label for="id_password_again" class="required">
				再输入密码:
			</label>
			{{form.password_again}}
		</div>
		<div class="submit-row">
			<label>&nbsp;</label><input type="submit" value="注册"/>
		</div>
</div>
{% endblock %}