accounts/urls.py
from django.conf.urls import patterns, include, url
from accounts import views
urlpatterns = patterns('',
  url(r'^register/', views.SignUpView.as_view(), name = 'register'),
  url(r'^login/', 'django.contrib.auth.views.login', {'template_name':'accounts/login.html'}, name = 'login'),
  url(r'^logout/', 'django.contrib.auth.views.logout', {'template_name':'accounts/logged_out.html'}, name = 'logout'),
  url(r'^profile/', views.profile, name = 'profile'),
)

msgboard/urls.py
from django.conf.urls import patterns, include, url
from msgboard import views

urlpatterns = patterns(
    '',
    url(r'^list/(?P<page>\d+)$', views.list, name = 'list'),
    url(r'^agree/$', views.agree, name = 'agree'),
    url(r'^post/$', views.post, name = 'post')
)

wujing/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'wujing.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^auth/', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace = 'accounts')),
    url(r'^chatroom/', include('chatroom.urls', namespace = 'chatroom')),
    url(r'^board/', include('msgboard.urls', namespace = 'msgboard')),
    url(r'^psytest/', include('psytest.urls', namespace = 'psytest')),
)

msgboard/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class BoardMsg(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='+')
    title = models.CharField(max_length = 200)
    content = models.TextField()
    tag = models.CharField(max_length = 200)
    agreeTimes = models.IntegerField(default = 0)
    created = models.DateTimeField()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = '留言'
        verbose_name_plural = verbose_name

class MsgTag(models.Model):
    text = models.CharField(max_length = 200)

    def __str__(self):
        return self.text
    
    class Meta:
        verbose_name = '标签'
        verbose_name_plural = verbose_name
    

msgboard/forms.py
from django import forms

class BoardMsgForm(forms.Form):
    title = forms.CharField()
    content = forms.CharField(widget = forms.Textarea)
    tag = forms.CharField()

msgboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import Http404, HttpResponse
from msgboard import models
from msgboard import forms

# Create your views here.
def list(request, page):
    contact_list = models.BoardMsg.objects.order_by('-created')
    paginator = Paginator(contact_list, 20)
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        contacts = paginator.page(1)
    except EmptyPage:
        contacts = paginator.page(paginator.num_pages)
    return render(request, 'msgboard/list.html', {
        'contacts': contacts,
        'form': forms.BoardMsgForm()
    })


@csrf_exempt
def agree(request):
    if 'id' not in request.POST:
        raise Http404
    contact = get_object_or_404(models.BoardMsg, pk = request.POST['id'])
    contact.agreeTimes += 1
    contact.save()

    return HttpResponse(contact.agreeTimes)

@login_required
def post(request):
    if request.method == 'GET':
        return render(request, 'msgboard/post.html', {
            'form': forms.BoardMsgForm(),
            'msg_tags': models.MsgTag.objects.all()
        })
    form = forms.BoardMsgForm(request.POST)
    if form.is_valid():
        c = models.BoardMsg(user = request.user,
                            title = form.cleaned_data['title'],
                            content = form.cleaned_data['content'],
                            tag = form.cleaned_data['tag'],
                            created = timezone.now())
        c.save()
        return redirect('msgboard:list', page = 1)
    else:
        return render(request, 'msgboard/post.html', {
            'form': form,
            'msg_tags': models.MsgTag.objects.all()
        })

msgboard/templates/msgboard/list.html
{% extends 'msgboard/main.html' %}
{% load staticfiles %}
{% block javascript %}
<script src="{% static 'msgboard/js/msgboard.js' %}"></script>
<script>
	function agree_msg(id) {
	$.post("{% url 'msgboard:agree' %}", {id:id}, function(data) {
  $("#agree_msg_" + id).html(data);
	});
	return false;
	}
</script>
{% endblock %}

{% block content %}
<div class="treehole">
	<div class="tree_title">
		<p>用另一种方式去放下,</p>
		<a href="{% url 'msgboard:post' %}"><input type="button" value="请来这里留言" class="btn_msg" /></a>
	</div>
	{% for item in contacts.object_list %}
	<div class="tree_thread">
		<img src="{% static 'msgboard/images/samp_pic_03.jpg' %}" class="portrait" />
		<p><b>{{item.title}}</b></p>
		<p>{{item.content}}</p>
		<h3>{{item.user.username}} : {{item.created | date:"SHORT_DATE_FORMAT"}}</h3>
		<span>
			<a href="javascript:" onClick="agree_msg({{item.id}});"><img src="{% static 'msgboard/images/icon_agree.png' %}"/></a>
			<span id="agree_msg_{{item.id}}">{{item.agreeTimes}}</span>
		</span>
	</div>
	{% endfor %}
	<div class="page_list">
		<p>
			{% if contacts.has_previous %}
			<a href="{% url 'msgboard:list' contacts.previous_page_number %}">上一页</a>
			{% endif %}
			{% for item in contacts.paginator.page_range %}
			<a href="{% url 'msgboard:list' item %}">{{ item }}</a>
			{% endfor %}
			{% if contacts.has_next %}
			<a href="{% url 'msgboard:list' contacts.next_page_number %}">下一页</a>
			{% endif %}
		</p>
	</div>
</div>
{% endblock %}

msgboard/templates/msgboard/main.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>晨曦心理</title>
<script src="{% static 'msgboard/js/jquery.min.js' %}"></script>
<script src="{% static 'msgboard/js_source/focus.js' %}"></script>
<script src="{% static 'msgboard/js_source/cx.js' %}"></script>
{% block javascript %}{% endblock %}
<link rel="stylesheet" href="{% static 'msgboard/images/style.css' %}" type="text/css" />
{% block stylesheet %}{% endblock %}
</head>
<body>
	<div class="block">
		<div class="navbar">
			<ul>
				<li class="sele"><a href="http://18.44.216.6/psycms">首页</a></li>
				<li class="m1"><a href="http://18.44.216.6/psycms/pnews/index.htm">心闻播报</a></li>
				<li class="m2"><a href="http://18.44.216.6/psycms/cyclopedia/index.htm">心理百科</a></li>
				<li class="m3"><a href="http://18.44.216.6/psycms/ptest/index.htm">心理测试</a></li>
				<li class="m4"><a href="http://18.44.216.6/bbs">心理论坛</a></li>
				<li class="m5"><a href="#">心海拾贝</a></li>
				<li class="m6"><a href="http://18.44.216.6/psycms/pheart/index.htm">心灵有约</a></li>
			</ul>
			<ul class="submenu s1">
				<li><a href="http://18.44.216.6/psycms/work/index.htm">工作动态</a></li>
				<li><a href="http://18.44.216.6/psycms/boss/index.htm">领导讲话</a></li>
				<li><a href="http://18.44.216.6/psycms/policy/index.htm">政策法规</a></li>
				<li><a href="http://18.44.216.6/psycms/pnotes/index.htm">公告通知</a></li>
			</ul>
			<ul class="submenu s2">
				<li><a href="http://18.44.216.6/psycms/pzt/index.htm">心理专题</a></li>
				<li><a href="http://18.44.216.6/psycms/pedu/index.htm">心理知识</a></li>
				<li><a href="http://18.44.216.6/psycms/ptrain/index.htm">心理行为训练</a></li>
				<li><a href="http://18.44.216.6/psycms/ptalk/index.htm">经验交流</a></li>
				<li><a href="http://18.44.216.6/psycms/pfx/index.htm">案例分析</a></li>
			</ul>
			<ul class="submenu s3">
				<li><a href="http://18.44.216.6/psycms/cel/index.htm">心理测量</a></li>
				<li><a href="http://18.44.216.6/psycms/qwcs/index.htm">趣味测试</a></li>
			</ul>
			<ul class="submenu s5">
				<li><a href="{% url 'msgboard:list' 1 %}">树洞</a></li>
				<li><a href="http://18.44.216.6/psycms/fm/index.htm">照片墙</a></li>
				<li><a href="http://18.44.216.6/psycms/humor/index.htm">治愈系</a></li>
				<li><a href="http://18.44.216.6/psycms/wall/index.htm">心理游戏</a></li>
				<li><a href="http://18.44.216.6/psycms/cure/index.htm">心理影院</a></li>
			</ul>
			{% if not user.is_authenticated %}
			<div class="btn_login">
				<span><a href="{% url 'accounts:login' %}?next={% url 'msgboard:list' 1%}">登录</a></span>
				<span><a href="{% url 'accounts:register' %}">注册</a></span>
			</div>
			{% endif %}
		</div>
	</div>
	<div class="block grey">
		<div class="search">
			<img src="{% static 'msgboard/images/logo.gif' %}" class="logo" />
			<img src="{% static 'msgboard/images/samp_banner_1.gif' %}" class="banner_top" />
		</div>
	</div>
	<div class="block">
		<div class="page_body">
			<div class="banner2">
				<img src="{% static 'msgboard/images/samp_banner_2.gif' %}" />
			</div>
			<div class="crumb">
				<p>
					<a href="http://18.44.216.6/psycms">首页</a> &gt; 
					<a href="{% url 'msgboard:list' 1 %}">树洞</a>
				</p>
			</div>
			<div class="content_box">
				<div class="content_left">
					{% block content %}
					{% endblock %}
				</div>
				<div class="content_right">
					<div class="menu_right">
						<ul>
							<li><a href="{% url 'msgboard:list' 1 %}" class="selected">树洞</a></li>
							<li><a href="http://18.44.216.6/psycms/fm/index.htm">照片墙</a></li>
							<li><a href="http://18.44.216.6/psycms/humor/index.htm">治愈系</a></li>
							<li><a href="http://18.44.216.6/psycms/wall/index.htm">心理游戏</a></li>
							<li><a href="http://18.44.216.6/psycms/cure/index.htm">心理影院</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="block">
		<div class="bott">
			<ul>
				<li><a href="">关于我们</a></li>
				<li><a href="">加入我们</a></li>
				<li><a href="">联系我们</a></li>
				<li><a href="">免责声明</a></li>
				<li><a href="">友情链接</a></li>
				<li><a href="">网站地图</a></li>
				<li><a href="">手机版</a></li>
				<li><a href="">手机应用</a></li>
				<li><a href="">投稿</a></li>
			</ul>
			<p>&reg; 2005-2014 xinli001.com All Rights Reserved. 粤ICP备12051153号 安全联盟</p>
		</div>
	</div>
</body>
</html>

msgboard/templates/msgboard/post.html
{% extends 'msgboard/main.html' %}
{% block content %}
<div class="treehole">
	<div class="tree_title">
		<p>在树洞中说出心中的<span>秘密</span>。</p>
	</div>
	<div class="tree_thread_txt">
		<form action="{% url 'msgboard:post' %}" method="post">
			{% csrf_token %}
      <h4>带*为必填项</h4>
			<p>
				<font><b>*</b>标题：</font>
				<input type="text" class="input_1" name="title" value="{% if form.title.value %}{{ form.title.value }}{% endif %}"/>
			</p>
			<p>
				{% for error in form.title.errors %}
				<i>{{error}}</i>
				{% endfor %}
			</p>
			<p><font><b>*</b>内容：</font>
				<textarea class="input_text" name="content">{% if form.content.value %}{{ form.content.value }}{% endif %}</textarea>
			</p>
			<p>
				{% for error in form.content.errors %}
				<i>{{error}}</i>
				{% endfor %}
			</p>
			<p><b>*</b>秘密类别:
				{% for item in msg_tags %}
				<input type="radio" 
							 class="checkbox" name="tag" 
							 value="{{ item.text }}"
							 {% if item.text == form.tag.value %}checked{% endif %}>
				{{ item.text }}
				{% endfor %}
      </p>
			<p>
				{% for error in form.tag.errors %}
				<i>{{error}}</i>
				{% endfor %}
			</p>
			<!--
					<p>
						<input type="checkbox" />
						匿名发表
					</p>
					-->
			<p><span><input type="submit" value="提交" class="submit_btn" /></span></p>
		</form>
	</div>
</div>
{% endblock %}