accounts/urls.py
from django.conf.urls import patterns, include, url
from accounts import views
urlpatterns = patterns('',
  url(r'^register/', views.SignUpView.as_view(), name = 'register'),
  url(r'^login/', 'django.contrib.auth.views.login', {'template_name':'accounts/login.html'}, name = 'login'),
  url(r'^logout/', 'django.contrib.auth.views.logout', {'template_name':'accounts/logged_out.html'}, name = 'logout'),
  url(r'^profile/', views.profile, name = 'profile'),
)

chatroom/urls.py
from django.conf.urls import patterns, include, url
from chatroom import views

urlpatterns = patterns('',
                       url(r'^room/$', views.room_admin, name = 'room_admin'),
                       url(r'^room/(?P<name>[^/]+)', views.room, name = 'room'),
                       url(r'^push/', views.push, name = 'push'),
                       url(r'^poll/', views.poll, name = 'poll'),
                       url(r'^go-room/', views.go_room, name = 'go_room'),)

wujing/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'wujing.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^auth/', include('django.contrib.auth.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('accounts.urls', namespace = 'accounts')),
    url(r'^chatroom/', include('chatroom.urls', namespace = 'chatroom')),
    url(r'^board/', include('msgboard.urls', namespace = 'msgboard')),
    url(r'^psytest/', include('psytest.urls', namespace = 'psytest')),
)

chatroom/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User
import datetime

class ChatUserManager(models.Manager):
    def get_channel(self, name):
        try:
            user = User.objects.get(username = name)
        except User.DoesNotExist:
            return None
        return self.get_user(user)

    def get_user(self, user, id = 0):
        now = timezone.now();
        if not user.is_authenticated():
            user = None
            name = '匿名'
            query = self.filter(id = id, user = None)
        else:
            name = user.username
            query = self.filter(user = user)
        query = query.filter(user_type = ChatUser.CHATUSER)
        try:
            data = query.get()
        except ChatUser.DoesNotExist:
            data = ChatUser(name = name, user_type = ChatUser.CHATUSER,
                            user = user, created = now, last_access = now)
            data.save()
        return data

class MessageManager(models.Manager):
    def push_message(self, user, target, message):
        now = timezone.now()
        data = Message(target = target, source = user, message = message,
                       created = now)
        data.save()
        return data

    def poll_message(self, user, target):
        dialogue = Dialogue.objects.get_dialogue(user, target)
        query = self.exclude(source = user).filter(target = user,
                            created__gt = dialogue.last_access)
        if target is not None:
            query = query.filter(source = target)
        query = query.order_by('created')
        if query.last():
            dialogue.last_access = query.last().created
            dialogue.save()
        return query

class DialogueManager(models.Manager):
    def join_user(self, user, target):
        if not (user.id == target.id or 
                target.user_type == ChatUser.CHANNEL and user.user is not None and user.user.is_staff):
            return None
        try:
            data = self.get(owner = user, target = target)
        except Dialogue.DoesNotExist:
            now = timezone.now()
            data = Dialogue(owner = user, target = target, right = 'R', last_access = now)
            data.save()
        return data

    def get_dialogue(self, user, target):
        try:
            dialogue = Dialogue.objects.get(owner = user, target = target)
        except Dialogue.DoesNotExist:
            dialogue = Dialogue(owner = user, target = target, right = 'R',
                                last_access = datetime.datetime.fromtimestamp(0))
            dialogue.save()
        return dialogue
        

# Create your models here.
class ChatUser(models.Model):
    UNKNOWN = 0
    CHATUSER = 1
    CHANNEL = 2
    USER_TYPE_CHOICES = (
        (UNKNOWN, '未知'), (CHATUSER, '用户'), (CHANNEL, '频道'),)

    name = models.CharField(max_length = 100)
    user_type = models.IntegerField(choices = USER_TYPE_CHOICES, default=UNKNOWN)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null = True, related_name='+')
    created = models.DateTimeField()
    last_access = models.DateTimeField()

    objects = ChatUserManager()
    
class Message(models.Model):
    target = models.ForeignKey(ChatUser)
    source = models.ForeignKey(ChatUser, related_name='+')
    message = models.TextField()
    created = models.DateTimeField()

    objects = MessageManager()

class Dialogue(models.Model):
    owner = models.ForeignKey(ChatUser)
    target = models.ForeignKey(ChatUser, null = True, related_name='+')
    right = models.CharField(max_length = 80)
    last_access = models.DateTimeField()

    objects = DialogueManager()

chatroom/forms.py
from django import forms
from django.forms import widgets

class PushMessageForm(forms.Form):
	target = forms.IntegerField()
	message = forms.CharField()

	

chatroom/views.py
import json
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import user_passes_test
from django.http import Http404, HttpResponse
from chatroom import models
from chatroom import forms
# Create your views here.

def go_room(request):
    if 'name' in request.GET:
        name = request.GET['name']
    else:
        raise Http404
    if request.user.is_authenticated():
        return redirect('chatroom:room', name = name)
    chatroom_url = reverse('chatroom:room', args=(name,))
    return render(request, 'chatroom/go-room.html' , 
                  {'chatroom_name':name, 'chatroom_url':chatroom_url})

def room(request, name):
    user = models.ChatUser.objects.get_user(request.user, 
                                            request.session.get('chat_user_id', 0))
    request.session['chat_user_id'] = user.id
    data = {'chat_user': user}
    if name is not None:
        target = models.ChatUser.objects.get_channel(name)
    else:
        target = None
    if target is not None:
        data['chat_target'] = target
    return render(request, 'chatroom/room.html', data)


@user_passes_test(lambda user:user.is_staff)
def room_admin(request):
    return room(request, None)

@csrf_exempt
def push(request):
    form = forms.PushMessageForm(request.POST)
    user = models.ChatUser.objects.get_user(request.user, 
                                            request.session.get('chat_user_id', 0))
    request.session['chat_user_id'] = user.id
    if not form.is_valid():
        return HttpResponse(json.dumps({'error':form.errors}))
    try:
        target = models.ChatUser.objects.get(pk = form.cleaned_data['target'])
    except models.ChatUser.DoesNotExist:
        raise Http404
    msg = models.Message.objects.push_message(user, target, form.cleaned_data['message'])
    data = {'id': msg.id, 'target': msg.target.id, 'source': msg.source.id,
            'name': chat_user_name(msg.source), 'receiver': chat_user_name(msg.target), 'message':msg.message}
    return HttpResponse(json.dumps(data))

def chat_user_name(user):
    if user.user is None:
        name = '%s%d' % (user.name, user.id)
    else:
        name = user.user.username
    return name

@csrf_exempt
def poll(request):
    user = models.ChatUser.objects.get_user(request.user, 
                                            request.session.get('chat_user_id', 0))
    request.session['chat_user_id'] = user.id
    if 'id' in request.POST:
        try:
            target = models.ChatUser.objects.get(pk = request.POST['id'])
        except models.ChatUser.DoesNotExist:
            raise Http404
    else:
        target = None
    message_list = models.Message.objects.poll_message(user, target)
    data = []
    for item in message_list:
        msg = {'id': item.id, 'target': item.target.id, 'source': item.source.id,
               'name': chat_user_name(item.source), 'receiver': chat_user_name(item.target), 'message':item.message}
        data.append(msg)
    return HttpResponse(json.dumps({'name': chat_user_name(user), 'data':data}))

            

chatroom/templates/chatroom/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}"/>
		<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% static "css/ie.css" %}" /><![endif]-->
		{% block extrastyle %}{% endblock %}
		<script src="{% static 'js/jquery.min.js' %}"></script>
		{% block extrahead %}{% endblock %}
	</head>
	<body id="container">
		<!-- Header -->
		<div id="header">
			<div id="branding">
				{%block branding %}{% endblock %}
			</div>
			{% if user.is_active %}
			<div id="user-tools">
				{% block welcome-msg%}{% endblock %}
				{% block userlinks %}{% endblock %}
			</div>
			{% endif %}
			{% block nav-global %}{% endblock %}
		</div>
		<!-- END Header-->
		{% block breadcrumbs %}{% endblock %}

		<!-- Content -->
		<div id="content" class="{% block coltype %}{% endblock %}">
			{% block pretitle %}{% endblock %}
			{% block content_title %}{% endblock %}
			{% block content %}{% endblock %}
			{% block sidebar %}{% endblock %}
		</div>
		<!-- END Content -->

		{% block footer %}{% endblock %}
	</body>
</html>

chatroom/templates/chatroom/go-room.html
{% extends "chatroom/base.html" %}

{% block title %}访问聊天室{% endblock %}

{% block branding %}<h1>访问聊天室</h1>{% endblock %}

{% block content %}
<div>
	<h1>欢迎您访问聊天室</h1>
	您如果需要以用户身份访问，请点击
	<a href="{% url 'accounts:login' %}?next={{chatroom_url}}">登入</a>
	，或者以
	<a href="{{chatroom_url}}">匿名</a>
	方式访问。
</div>
{% endblock %}

chatroom/templates/chatroom/room.html
{% extends "chatroom/base.html" %}
{% load staticfiles %}
{% block title %}聊天室{% endblock %}

{% block extrahead %}
<script src="{% static 'js/knockout.js' %}"></script>
<script src="{% static 'js/jquery.cookie.js' %}"></script>
<script src="{% static 'chatroom/js/chatroom.js' %}"></script>
<script>
	$(document).ready(function() {
	document.chatroomModule = new ChatroomModule("{% url 'chatroom:poll' %}",
	"{% url 'chatroom:push' %}");
	ko.applyBindings(document.chatroomModule, $("#chatroom").get(0));
	{% if chat_target %}
	document.chatroomModule.putReceiver({{chat_target.id}},
	"{{chat_target.name}}");
	{% endif %}
	document.chatroomModule.pollMessage();
	setInterval(function() {
	document.chatroomModule.pollMessage();
	}, 5000);
	});
</script>
{% endblock %}

{% block branding %}
<h1>聊天室</h1>
{% endblock %}

{% block coltype %}{% endblock %}

{% block content %}
<div id="chatroom" style="width:100%;">
	<div "object-tools"><strong>当前用户:</strong><span data-bind="text: username"></span></div>
	<hr/>
	<div data-bind="foreach: messageList" style="width:100%; height:600px;">
		<div>
			[<strong><span data-bind="text: name, click: $parent.clickReceiver"></span></strong>]
			对
			[<strong><span data-bind="text: receiver"></span></strong>] 说:
			<span data-bind="text: message"></span>
		</div>
	</div>
	<div>
		<strong><span style="width:100px;" data-bind="text: receiver"></span></strong>
		<input type="text" style="width:600px;" data-bind="value: message"/>
		<button data-bind="click: clickSendBtn, enable: isSending != true && receiverId">发送</button>
		<button data-bind="click: clickCleanBtn">清屏</button>
	</div>
</div>
{% endblock %}